In [7]:
python_list = [2, 3, 4, 5, 6, 7]
print(python_list)

import numpy as np

numpy_array = np.array([1,2,3,4,5])
print(numpy_array)

[2, 3, 4, 5, 6, 7]
[1 2 3 4 5]


In [8]:
marks1 = 85 
marks2 = 90 
marks3 = 87
marks4 = 91
marks5 = 75

marks = [90, 91 , 92 , 85 , 76]

In [11]:
import numpy as np


ar_2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30],
])

print(ar_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
# craeting arrays from python lists 

import numpy as np 
arr = np.array([1,2,3,4])
print(arr)

# np.zeros(shape)  (3) ,,fir id , (3,3) 2d
import numpy as np 

ones_array = np.ones((1 , 2))
print(ones_array)

filled_Array = np.full



[1 2 3 4]
[[1. 1.]]


NameError: name 'A' is not defined